statist:
  address: "0.0.0.0:8083"

worker:
  type: "audit"
  time: 1
  threads: 50
  urls: [{
            url: "http://localhost:8080/analytics",
            method: "POST",
            id: false,
            body: true,
            b: '{
              "module" : "settings",
              "type" : "alert",
              "event" : "click",
              "name" : "подтверждение выхода",
              "data" : {"action" : "cancel"}
            }'
          }]